### ISSUE TITLE
Proposal for component slots

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-app/builder#1767]
## The Problem

The current component system works for only basic templating. For example, you can't create a useful layout component right now.

## The solution

We need what's the equivalent of slots in templating tools. In Vue they are called slots, in Rails this is done through partials, in Laravel you have component slots. And in React this functionality is filled mostly by render props or by passing components as props/in context.

## Implementation

I can imagine 2 ways to do this

### 1. The explicit way
Users explicitly define an API for their components, similar to how we have an api for Atoms props. For example:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/57956282/187932904-ee36b004-bbb9-4671-9119-4faf59705218.png">

For slots we can use existing types, like RenderPropsType, ReactNodeType, ElementType.
This api serves as the place of truth for defining the inputs that a component takes. 
The benefit of this is that that's not only applicable for slots, but we can also assign other props to the component, like strings, numbers, etc.
We use this interface to generate a form for the component, just like we do for atoms.

The next part is to be able to assign this slot to a particular element
One way to do that is to bind it to props. Say that we have a Div atom with this API
<img width="959" alt="image" src="https://user-images.githubusercontent.com/57956282/187933534-e081da3a-0039-45b5-99b1-8e831d7adfdf.png">

Now we only need to connect `heroContent` from the Layout's API to the `children` of the Divs API. The easiest way I imagine is to bind it as we bind global state variables. 
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/57956282/187933790-70b0db34-6773-4a60-9dda-604fc74fb4db.png">

This would require modifying the prop evaluating code to take into account the current component that the element is in and its props.

### The implicit way
We create a new Atom Type, for example named `Slot`.
The user creates a new element as usual and assigns it an Atom with type Slot:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/57956282/187934585-3e701b16-624b-48ab-aef7-989c6c449acc.png">

Then on the component instance, we render a form that has all of the elements inside it with atom type Slot and we allow the user to pick a Component to render for them.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/57956282/187935140-50fc67cc-ab9d-425f-8c5b-dd23bd7f4494.png">

The data from this form is stored on the component instance either as a separate field or as a special prop. It has the shape of a key-value object where the key is the id of the Slot-atomed element and the value is the component id to render. This is then used when evaluating the props to render the specific component instead of the slot-atomed element.

This approach seems simpler, but it's less flexible since the user can't define other component props other than slots. 

#### Note
In both implementations, we can additionally add the ability to directly drag and drop an element to the slot to avoid creating a component for it.

Any thoughts or other ideas?

**Comment by webberwang** [comment]
I like approach one better, it requires less additional features to accomplish the goal & is more capable.

A side question is, currently prop binding is global which makes it more flexible.

But should we restrict only props that are passed into a component to be visible to the props below?

**Comment by antonmihaylov** [comment]
Yeah it has to be restricted or it would be a mess otherwise if the first approach is used. The global prop binding could be kept of course, the component one could use React Context or some other mechanism to containerize it to specific components

**Comment by melhamin** [comment]
@antonmihaylov can you explain why it needs to be restricted?

> Yeah it has to be restricted or it would be a mess otherwise if the first approach is used. The global prop binding could be kept of course, the component one could use React Context or some other mechanism to containerize it to specific components

**Comment by webberwang** [comment]
Thinking out loud here, at each level of parent-child prop passing, we could have a filter. Imagine a list of all props, we could omit a prop from getting passed down with some sort of UI.

This is equivalent of whether to pass props down in code (which is manually binding props to react jsx)

**Comment by antonmihaylov** [comment]
@melhamin because if you have nested components it would be easy to get mixed up if both of them have the same keys

**Comment by assimhabeek** [comment]
I prefer the first approach a well defined component API not just for slots but all data types. 
- Feels more natural and similar to any React component.
- Less effort for user, one time api change.
- Brings more structure and facilitates component usage by users. (when an element is an instance of a component we could have props form similar to atoms)
- Maybe in the future we add a type validation by having props of type `ReactNodeType<Component API A>` or `RenderPropsType<Component API B>`. (this seems far right now). 

I want to point out that the first approach is achievable right now by `RenderPropsType` and `ReactNodeType` expressions made by @vladyslav-polishchuk using the global state variables. However, The only way right now to have a dumb component is to use prop map binding which doesn't have autocomplete for `source-key` because it doesn't know what should be the props of the component. but if we made prop map binding reads props list from component api this will solve the issue.

In the second approach, I disagree that data should be stored on component. the data is related to the instance. so it should be stored in the component instance element (or it could be a relation property ) which means that having form on the component it self is wrong.

**Comment by webberwang** [comment]
Here is the steps that I see:

1. Add a `children` prop to all element, where an expression can be created
2. This will read from component API
3. Any data passed to the component root will be forwarded to the appropriate children
