### ISSUE TITLE
API service integration

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1844]
There are 2 portions to interacting with an API.

# Resource Integration

We would create a form that contains all the required information to connect to an API service (Supabase) for example. Then an Api Action could use this integration.

# GraphQL Codegen
Similar to our GraphQL codegen, we declare gql queries as data requirements, and a function is generated for us to use.

For the platform, we'll declare gql queries, and an Api Action will be generated for the forms to use.

# Interface Form Generation
We'll need the form to connect to the API, so we'll build an interface which generates this form (to connect to the Api Action)

**Comment by assimhabeek** [comment]
first we tried to expose NextJs `getServerSideProps` thinking it may help in protecting routes when we use SSR auth solution like this.
```
async function (context) {
  const supabase = await import('@supabase/supabase-js');

  // do auth logic here
  
  return {
    props: {
      supabase
    },
    redirect: undefined,
    notFound: false,
  }
}
```
 but this didn't work because following : 
- Providers auth will require redirection and reading from url which requires client to do that 
- Supabase instance is not serializable so can't pass from  `getServerSideProps` to state
- Session storage will happen only on client so we should have client side solution directly.

**Comment by webberwang** [comment]
I think we would integrate https://supabase.com/docs/guides/auth/auth-helpers/nextjs, basically would be hardcoded into our platform

**Comment by assimhabeek** [comment]
The problem with using https://supabase.com/docs/guides/auth/auth-helpers/nextjs is that it work only by reading from env which is not acceptable for us. since each user will have different supabase app. but I see that when redirection happens query params are accessible via context. which means we could use supabase client lib to have same behavior on sever side without the need to auth helpers. it is something I will try to achieve.  
![image](https://user-images.githubusercontent.com/33001357/209734944-908a48ab-72e3-4f99-bf13-102f0a34bb0c.png)
