### ISSUE TITLE
Apps are not rendered after deleting an element that uses a component as prop

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#1918]
## Current Behavior
After deleting an element that uses a component in its props, the page and the whole app is not rendered anymore. The error is thrown even for the newly created apps. 

## Steps to Reproduce

https://user-images.githubusercontent.com/48331678/194728190-22b6d7c5-5b9a-4b5b-9711-d9716d2ebfd5.mov

**Comment by mohasarc** [comment]
The deletion of the `Card` element caused, for some reason, the deletion of the root element of `AntDesignTypographyTitle`. Because components are visible in all the apps (the are not app specific) and because the root of a component is a non-nullable fiels, nothing renders.

Still it's weird that deleting an element causes the deletion of another element.

**Comment by melhamin** [comment]
Ok. Thanks will look into it.

**Comment by melhamin** [comment]
@mohasarc the issue was with how we used to convert element to component. The `rootElement` of the intermediate element that we create while conversion gets deleted after deleting the element, which would cause the error. I believe this PR #1919 fixes the issue. Can you also check?

**Comment by mohasarc** [comment]
Yeah, problem seems to be solved!
