### ISSUE TITLE
Add nested table for dependent types

### ISSUE THREAD

**Issue by webberwang** [codelab-app/builder#1925]
Say we want to edit the shape enum type inside the button interface, there isn't a way to do that.

![AntDesignButton_API___Codelab](https://user-images.githubusercontent.com/26264925/195203038-6ddf15de-b403-4593-bcf6-bf6673d98b69.jpg)

We should use antd nested table to display those types under the field

**Comment by mohasarc** [comment]
Do we want this behaviour only for enum types or for any field type?

**Comment by mohasarc** [comment]
It seems like we have two options:
- Add a nested table listing the values and allowing editing them
- Add a button under `Action` column to update the type that opens `UpdateTypeModal`.

**Comment by webberwang** [comment]
Well the motivation was that it's hard to edit dependent types, we would have to go to types table and search for it.

I think any related type would show not just enums, recursion should be okay too we'll just display a flat list

The modal I think doesn't help with visualization the data though

**Comment by webberwang** [comment]
After some thinking, we can group into union/interface & the rest. Seeing that the rest only has 1 type, we can add the button to action column (as your suggestion)

For union/interface we'll just make them navigate to the type (so unchanged)

**Comment by mohasarc** [comment]
Another idea: Since our concern is visibility and ease of access, how about we have only one table, inside which we have nested tables for fields of type interface (or memebers of a union). In this case we don't need a separate page for interfaces

![Types-Table-Design drawio](https://user-images.githubusercontent.com/51242349/196031253-d15a9a28-9c79-4bdc-a25f-4f88a8aaf726.png)

In the example above, we have 8 high level Types: `Person`, `Union`, `String`, `Integer`, `Float`, `House`, `Univerisy`, and `Library`; expanding person'a fields we see house, name, and cv; because house is of interface type, we can also expend its fields to see address and area. On the other hand, we can expend union type to see its members, each of which can be expanded as well if it was of interface or union type.

Fields, and Type edit buttons behave the same as what we have now.

**Comment by webberwang** [comment]
Nice diagram! This sounds like a great idea, to reduce down to a single table. Perhaps we could do without the indentation? Since that would help with recursive interfaces
