### ISSUE TITLE
Edit Atom API button not working as expected

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#2053]
## Current Behavior
Clicking on `Edit [Atom] API` doesn't open the atom api.

## Video Showing Bug
https://user-images.githubusercontent.com/48331678/203968317-88f6ae8c-9952-4dcb-ac0b-e5b67e298095.mov

**Comment by M-Abozaid** [comment]
What's the expected behavior, should the selected type be highlighted in the types table?

**Comment by melhamin** [comment]
It used to work like this. 

https://user-images.githubusercontent.com/48331678/205328597-5da86f91-d905-46ae-9da3-a2b296e8ac25.mov

**Comment by M-Abozaid** [comment]
Current implementation of highlighting type using `typeId` query param only works if the type is in the first page of results.

Solution: get the index of the type with `typeId` and use that to change to the page where the type exist.

Plan:
- Create a cypher to get the index of type given `typeId`
- Add `typeId` option to `GetBaseTypesOptions`
- Modify the `baseTypes` resolver to use the `typeId` if provided and return the page that contains that type instead of using offset.
- Return the offset so the frontend can show the correct page number.
- Update the forntend to send the `typeId` and use the offset from the query result if available

**Comment by jethrocabaluna** [comment]
@webberwang I think this has already been fixed with https://github.com/codelab-app/builder/pull/2115
[_app-Builder-Codelab.webm](https://user-images.githubusercontent.com/27695022/210533641-3fd7f09e-8c9e-4eac-8894-b7fb57e1426a.webm)

**Comment by jethrocabaluna** [comment]
[_app-Builder-Codelab.webm](https://user-images.githubusercontent.com/27695022/210537299-e2ffbfd8-6774-49fd-9f25-e7d01ac7913f.mp4)

**Comment by webberwang** [comment]
Closed by #2115
