### ISSUE TITLE
Error editing type

### ISSUE THREAD

**Issue by melhamin** [codelab-app/builder#2090]
## Current Behavior
Editing `Type` field on a type throws error.

## Video Showing Bug

https://user-images.githubusercontent.com/48331678/206287591-675bec6e-bb1e-4078-b555-ca2fca020c41.mov

**Comment by melhamin** [comment]
It seems to happen only if the `Types` page is opened in a separate tab.

**Comment by jethrocabaluna** [comment]
This bug is caused by https://github.com/codelab-app/builder/issues/2117. `typeRef` was not working because the fieldType data is not loaded and the `id` is needed for [rootRef](https://github.com/codelab-app/builder/blob/4916af3705dc046340c5095cdbe6593f4a589576/libs/frontend/domain/type/src/store/models/union-type.model.ts#L61) to work.

There is already an open PR https://github.com/codelab-app/builder/pull/2132 fixing the unloaded sub field types. This should also fix this bug where opening the edit modal is failing

[type-edit-modal-fixed.webm](https://user-images.githubusercontent.com/27695022/210787158-05a648e6-5dff-4e67-8291-7ea8b300f798.webm)
